// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Praksa2.Repo;

namespace Praksa2.Repo.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Praksa2.Repo.Models.SuperAdmin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("SuperAdmins");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Password = "admin123",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("Praksa2.Repo.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<byte[]>("Photo");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.Property<int?>("UsersID");

                    b.HasKey("ID");

                    b.HasIndex("UsersID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Praksa2.Repo.Models.Users", b =>
                {
                    b.HasOne("Praksa2.Repo.Models.Users")
                        .WithMany("UsersCollection")
                        .HasForeignKey("UsersID");
                });
#pragma warning restore 612, 618
        }
    }
}
